### ISSUE TITLE
The "path" argument must be of type string. Received an instance of Object

### ISSUE THREAD

**Issue by rtrembecky** [FogelAI/babel-plugin-transform-barrels#11]
Hi, me again 😄 Not to add more stuff to #8 as there's a lot already.

Issue:
`The "path" argument must be of type string. Received an instance of Object`

Quick stack:
```
      at Resolver.getFilePathFromPackageJson (../../node_modules/babel-plugin-transform-barrels/src/resolver.js:141:52)
      at Resolver.resolveAbsFilePath (../../node_modules/babel-plugin-transform-barrels/src/resolver.js:113:30)
      at Resolver.resolveNodeModules (../../node_modules/babel-plugin-transform-barrels/src/resolver.js:94:39)
      at Resolver.resolve (../../node_modules/babel-plugin-transform-barrels/src/resolver.js:52:29)
      at ../../node_modules/babel-plugin-transform-barrels/src/barrel.js:233:45
          at Array.forEach (<anonymous>)
```

The investigation tells me:
- the `cjsModule` and/or `esmModule` are objects, not paths
- it fails on e.g. `date-fns` package
- example `exportsObj`:
```ts
{
  absCjsFile: { types: './index.d.cts', default: './index.cjs' },
  absEsmFile: { types: './index.d.ts', default: './index.js' }
}
```
- coming from here: https://github.com/date-fns/date-fns/blob/main/package.json#L23-L32

Should be easy to fix. Maybe a `typeof cjsModule === 'string'` check and optional access like `cjsModule?.default` or something? Not sure what's the exact `package.json` > `exports` standard.

**Comment by FogelAI** [comment]
Hi @rtrembecky 

Thank you for your efforts and code suggestions. I really appreciate it.
I’ve made a new commit [refactor and small fixes](https://github.com/FogelAI/babel-plugin-transform-barrels/commit/7473d2c22acf2a7b443ae43b7b219140f621046a) that resolve the issue.

**Comment by FogelAI** [comment]
Hi @rtrembecky 

I have released a new version of the plugin (v1.0.23) that should resolve your issue.
Please update your version and let me know if it resolves your issue.
