### ISSUE TITLE
Cannot read properties of null (reading 'program')

### ISSUE THREAD

**Issue by rtrembecky** [FogelAI/babel-plugin-transform-barrels#12]
I know there's #2 already with the similar error message, but that issue was also iterated on many times, and the cause is probably different.
For the record, I got to this state by:
- commenting out mocks that cause my issues in #8 
- applying #9 and #10
- applying my code suggestion from #11

Error:
`Cannot read properties of null (reading 'program')`

Stack:
```
      at BarrelFile.createSpecifiersMapping (../../node_modules/babel-plugin-transform-barrels/src/barrel.js:242:19)
      at BarrelFile.handleExportAllDeclaration (../../node_modules/babel-plugin-transform-barrels/src/barrel.js:214:25)
      at ../../node_modules/babel-plugin-transform-barrels/src/barrel.js:259:18
          at Array.every (<anonymous>)
      at BarrelFile.createSpecifiersMapping (../../node_modules/babel-plugin-transform-barrels/src/barrel.js:242:32)
      at BarrelFile.handleExportAllDeclaration (../../node_modules/babel-plugin-transform-barrels/src/barrel.js:214:25)
      at ../../node_modules/babel-plugin-transform-barrels/src/barrel.js:259:18
          at Array.every (<anonymous>)
      at BarrelFile.createSpecifiersMapping (../../node_modules/babel-plugin-transform-barrels/src/barrel.js:242:32)
      at BarrelFilesPackage.getBarrelFile (../../node_modules/babel-plugin-transform-barrels/src/barrel.js:325:24)
      at Function.getBarrelFile (../../node_modules/babel-plugin-transform-barrels/src/barrel.js:399:43)
      at importDeclarationVisitor (../../node_modules/babel-plugin-transform-barrels/src/main.js:22:46)
      at PluginPass.call (../../node_modules/babel-plugin-transform-barrels/src/main.js:93:7)
```

Investigation:
- the last processed barrel file is `libs/mobile/test-utils/src/index.ts`, with content:
```ts
export * from './__mocks__/navigation';
export * from './testUtils';
```
- the stacktrace is basically:
- `BarrelFilesPackage.getBarrelFile('/Users/richard/repos/xxx/libs/mobile/test-utils/src/index.ts')`
- `barrelFile.createSpecifiersMapping()`
- 
```ts
BarrelFile.handleExportAllDeclaration(Node {
    type: 'ExportAllDeclaration',
    start: 40,
    end: 68,
    loc: SourceLocation {
      start: [Position],
      end: [Position],
      filename: undefined,
      identifierName: undefined
    },
    exportKind: 'value',
    source: Node {
      type: 'StringLiteral',
      start: 54,
      end: 67,
      loc: [SourceLocation],
      extra: [Object],
      value: './testUtils'
    },
    attributes: []
  })
```
- in `libs/mobile/test-utils/src/testUtils.tsx`, there's this code:
```ts
// re-export everything
// eslint-disable-next-line no-restricted-imports
export * from '@testing-library/react-native';

// override render method
export { customRender as render, customRenderHook as renderHook };
```
- next is `exportedAllFile.createSpecifiersMapping(true)` on the first import
-
```ts
BarrelFile.handleExportAllDeclaration(Node {
    type: 'ExportAllDeclaration',
    start: 3389,
    end: 3435,
    loc: SourceLocation {
      start: [Position],
      end: [Position],
      filename: undefined,
      identifierName: undefined
    },
    exportKind: 'value',
    source: Node {
      type: 'StringLiteral',
      start: 3403,
      end: 3434,
      loc: [SourceLocation],
      extra: [Object],
      value: '@testing-library/react-native'
    },
    attributes: [],
    trailingComments: [ [Object] ],
    leadingComments: [ [Object], [Object] ]
  })
```
- I logged the resolved object:
```ts
ResolvedPath {
  originalPath: '/Users/richard/repos/grpn/mbnxt/node_modules/@testing-library/react-native',
  absEsmFile: '',
  absCjsFile: '/Users/richard/repos/grpn/mbnxt/node_modules/@testing-library/react-native/build/index.js',
  packageJsonExports: false
}
```
- `absoluteExportedPath` is `''`, barrel is created for the empty path
- `exportedAllFile.createSpecifiersMapping(true)`
- `const barrelAST = AST.filenameToAST('')`
- `barrelAST` is null

**Comment by FogelAI** [comment]
Hi @rtrembecky 

I have released a new version of the plugin (v1.0.23) that should resolve your issue.
Please update your version and let me know if it resolves your issue.
